# Generated by Django 5.2.2 on 2025-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpense',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=7),
        ),
    ]
